apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-calt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0026-tenant/tkwch-fix-0075-0026-app/devfile-sample-calt@sha256:8e951404ebb7743a932b006775638f8e701a880811dff59f95b621b6039d6472
        name: my-nodejs
        resources: {}
status: {}
